bioswarm AI
Stellaris-Evolved/stellaris-evolved pull request #37
Opened 2023-11-19 15:23 UTC by Arpharnator

- new budgets
- tweaked old budget and overwrote some
- fixes to a few things to prevent softlocking

2023-12-09 22:45 UTC, adriangaro requested changes

2023-12-09 22:45 UTC, adriangaro commented on common/buildings/zz_evolved_manufacturing_buildings.txt
> +					resource_stockpile_compare = { resource = minor_artifacts value > 300 }
Wouldn't this be covered by the last allow check? If not, i would better use the variable from cost.

2023-12-09 22:45 UTC, adriangaro commented on common/decisions/zz_evolved_ecoworld_decisions.txt
> +		set_planet_flag = undergoing_ecoworld_project
prefix with `tec_`

2023-12-09 22:45 UTC, adriangaro commented on common/inline_scripts/economic_plans/inline_evolved_base_plan.txt
> +		scaling = yes
Can you move both scaling subplans after the initial ones

2023-12-09 22:45 UTC, adriangaro commented on common/scripted_triggers/zzz_evolved_ai_scripted_triggers.txt
> +		NOT = { has_planet_flag = undergoing_ecoworld_project }
same prefix with `tec_`

2023-12-09 22:45 UTC, adriangaro commented on common/scripted_triggers/zzz_evolved_ai_scripted_triggers.txt
> +				resource_stockpile_compare = { resource = alloys value > 1200 }
tbh i would move these checks probably to the allow, instead of polluting them for machines here. it would make it a bit more readable if those checks happened in the allow (although probably can refactor myself after).

2023-12-09 22:45 UTC, adriangaro commented on common/scripted_variables/!_evolved_ai_variables.txt
> +@tec_minimum_resources = 6000
`6000` is a bit excessive, especially since it would not help the ai specialize/build important stuff at game start. Probably 2/3k would be a bit of a better value (unless your tests showed otherwise in which case i am happy with that)

2023-12-09 22:45 UTC, adriangaro commented on common/traits/09_ascension_traits.txt
> +		"trait_hive_mind"
Lol, tbh should handle AI weights for this, never got the chance. Might want to apply to personality nullifiers too? (if they can even get that on cyber hives)

2023-12-09 23:01 UTC, Arpharnator commented on common/traits/09_ascension_traits.txt
> +		"trait_hive_mind"
done

2023-12-09 23:01 UTC, Arpharnator commented on common/scripted_variables/!_evolved_ai_variables.txt
> +@tec_minimum_resources = 6000
It look like a lot, but since that is for empires that change costs to something less valuable than minerals, AND that change starbase costs, i found that the budget allocated wasn't nearly enough at 3k, especially for the later upgrades of the capital building which can cost a really large amount for the budget with the starbases.

2023-12-09 23:01 UTC, Arpharnator commented on common/scripted_triggers/zzz_evolved_ai_scripted_triggers.txt
> +				resource_stockpile_compare = { resource = alloys value > 1200 }
Interestingly enough, the tec_ai_allow_energy_boosting_building is applied both for the allows and the ai bait part of the buildings, so it does both at the same time.

2023-12-09 23:01 UTC, Arpharnator commented on common/scripted_triggers/zzz_evolved_ai_scripted_triggers.txt
> +		NOT = { has_planet_flag = undergoing_ecoworld_project }
done

2023-12-09 23:01 UTC, Arpharnator commented on common/inline_scripts/economic_plans/inline_evolved_base_plan.txt
> +		scaling = yes
done

2023-12-09 23:01 UTC, Arpharnator commented on common/decisions/zz_evolved_ecoworld_decisions.txt
> +		set_planet_flag = undergoing_ecoworld_project
done

2023-12-09 23:01 UTC, Arpharnator commented on common/buildings/zz_evolved_manufacturing_buildings.txt
> +					resource_stockpile_compare = { resource = minor_artifacts value > 300 }
indeed, as such i have decided to change the check slightly to have a mult of 2 in order to replace this check (checking for the minimum amount doesn't work well unfortunately due to AI building minor artifact ships)

2023-12-10 14:00 UTC, adriangaro requested changes

2023-12-10 14:02 UTC, adriangaro commented on common/terraform/02_special_terraform_links.txt
> +@gaiaCost = 7500
Not sure about overwriting vanilla terraforming links, as this will cause issues with PD. I would remove these.

Also what would this achieve (a lot to review xd)?

2023-12-10 14:14 UTC, Arpharnator commented on common/terraform/02_special_terraform_links.txt
> +@gaiaCost = 7500
the reason I did this was because of the hive to normal planets terraformations, where the biohive would terraform back to a normal planet due to ai weights. It's quite troublesome if we don't overwrite, although i suppose the best way would be prevent them from the hiveworld AP or make some sort of identical planet class (but that also has its own problems).

2023-12-10 14:14 UTC, Arpharnator commented on common/policies/zzzzb_evolved_policies.txt
> +			#NOOOOOOOOOOOOOOOOOO Terrible AI empire killer
done

2023-12-10 14:14 UTC, Arpharnator commented on common/policies/zzzzb_evolved_policies.txt
> +			#Same here
yea they definitely do, especially since the thing is completely time based and has no regard for the current situation. Furhtermor the AI essentially never has enough amenities for this to be worthwhile (also it sucks).

2023-12-10 14:15 UTC, Arpharnator commented on common/inline_scripts/economic_plans/inline_evolved_base_plan.txt
> +	#Overwrite so bioswarm stops spamming pop production when in food deficit
yea you're gonna want to change the assembly buildings as well, since they have access to AI crack more or less unconditionally.

2023-12-10 14:15 UTC, Arpharnator commented on common/inline_scripts/economic_plans/inline_evolved_base_plan.txt
> +		set_name = "base pops biohive"
done

2023-12-10 14:20 UTC, adriangaro commented on common/districts/zz_evolved_gestalt_districts.txt
> +					job = agri_drone
this will break with angler jobs, probably might need a script value similar to the one for researcher jobs etc

2023-12-10 14:50 UTC, adriangaro commented on common/colony_automation_exceptions/zz_evolved_ai_exceptions.txt
> +						value > 0.54
use `value >= 0.55` for safety

2023-12-10 14:52 UTC, adriangaro commented on common/terraform/02_special_terraform_links.txt
> +@gaiaCost = 7500
Yeah, again i would remove this as it will break compat.
Terraform links are notorious to overwrite.

2023-12-10 14:54 UTC, Arpharnator commented on common/terraform/02_special_terraform_links.txt
> +@gaiaCost = 7500
alright, I might just block the hive worlds perk for now if biohive

2023-12-10 15:00 UTC, Arpharnator commented on common/colony_automation_exceptions/zz_evolved_ai_exceptions.txt
> +						value > 0.54
done

2023-12-10 15:00 UTC, Arpharnator commented on common/districts/zz_evolved_gestalt_districts.txt
> +					job = agri_drone
done

2023-12-10 20:14 UTC, adriangaro requested changes

2023-12-10 20:14 UTC, adriangaro commented on common/starbase_modules/zz_evolved_starbase_modules.txt
> +						AND = {
No need for the stacked ANDs

2023-12-10 20:14 UTC, adriangaro commented on common/starbase_modules/zz_evolved_starbase_modules.txt
> +							tec_is_biohive = yes
Same here

2023-12-10 21:09 UTC, Arpharnator commented on common/starbase_modules/zz_evolved_starbase_modules.txt
> +						AND = {
done

2023-12-10 21:09 UTC, Arpharnator commented on common/starbase_modules/zz_evolved_starbase_modules.txt
> +							tec_is_biohive = yes
done

2024-03-26 08:49 UTC, adriangaro requested changes

2024-03-30 17:21 UTC, adriangaro commented on common/buildings/zz_evolved_empire_buildings.txt
> +	ai_resource_production = {
the block in `resources` about zro should already cover this, guess won't hurt, but still

2024-05-18 01:23 UTC, closed without merging

2024-05-18 01:23 UTC, adriangaro commented
For easy fixes and rebasing, have cloned your branch into the repo, fixed/adjsuted and merged.
https://github.com/Stellaris-Evolved/stellaris-evolved/pull/42